name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - run: chmod +x ./gradlew
    - run: ./gradlew assembleDebug
        
    - uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: app/build/outputs/apk/debug/app-debug.apk
